### PR TITLE
Added one_hot() operator.

### PR DESCRIPTION
**Pull request by w-adamski**

### CODE REVIEW

**Comment by nolanliou** [comment]
@w-adamski Which kind of model needs this operation?

**Comment by herbakamil** [comment]
@nolanliou in our case it's a computer vision project but it could be anything - any situation where one of the inputs is categorical (NLP, classification of credit risk, etc.).

**Comment by herbakamil** [comment]
@nolanliou are there any problems with this PR? What do you think about it?

**Comment by nolanliou** [comment]
@herbakamil sorry for the late, I'll check the PR ASAP.

**Comment by nolanliou** [comment]
Thanks

**Comment by herbakamil** [comment]
Thank you :) It's nice to not have to maintain to many difference between our and master version of MACE :)

**Comment by nolanliou** [comment]
We removed the OpenCL code of one_hot, because it's not a common way to deal with the 1D input in OpenCL and the CPU version performance is better than OpenCL.

**Pull request merged**
