### PR TITLE
Support ADB IP devices

### PR DESCRIPTION
**Pull request by idstein**
Regex will not match ADB IP devices.

### CODE REVIEW

**Comment by nolanliou** [comment]
Thanks for your PR, please rebase the code.

**Comment by idstein** [comment]
Rebase is done

**Comment by nolanliou** [comment]
It seems the rebase is not correct. you could refer to https://stackoverflow.com/questions/7929369/how-to-rebase-local-branch-with-remote-master

**Comment by llhe** [comment]
After a correct git rebase there will only contains your own commits.

**Comment by idstein** [comment]
> After a correct git rebase there will only contains your own commits.

Fixed. Sorry there was some hick up with our branches.

**Pull request merged**
